var initModalWindows = require('../components/modal-window/modal-window')
var initAuthForm = require('../components/auth-form/auth-form')
var initMessageModal = require('../components/message-modal/message-modal')
var initCatalogList = require('../components/catalog-list/catalog-list')
var initTownSelector = require('../components/town-selector/town-selector')
var initProductCard = require('../components/product-card/product-card')
var initSearchLocation = require('../components/search-location/search-location')
var initSearchForm = require('../components/search-form/search-form')
var initBannerSlider = require('../components/banner-slider/banner-slider')
var initShopCategory = require('../components/shop-category/shop-category')
var initProductSlider = require('../components/product-slider/product-slider')
var initSimpleSlider = require('../components/simple-slider/simple-slider')
var initInstructionUse = require('../components/instruction-use/instruction-use')
require('../components/product-comments-media/product-comments-media')
require('../components/brand-page/brand-page')
require('../components/product-tabs/product-tabs')
require('../components/price-selector/price-selector')
require('../components/sharing-popup/sharing-popup')
require('../components/shop-category-filters/shop-category-filters')
require('../components/shop-category-sorting/shop-category-sorting')
require('../components/dropdown/dropdown')
require('../components/notify-product-modal/notify-product-modal')
require('../components/brand-search-index/brand-search-index')
require('../components/add-comment/add-comment')
require('../components/product-preview/product-preview')
require('../components/shop-terminal-modal/shop-terminal-modal')
require('../components/medecine-page/medecine-page')
require('../components/delivery-map/delivery-map')
require('../components/order-form/order-form')
require('../components/search-swich-filter/search-swich-filter')
require('../components/delivery-explore/delivery-explore')
require('../components/content-block/content-block')
require('../components/account/account-input/account-input')
require('../components/shop-terminal/shop-terminal')
require('../components/site-header/site-header')
require('../components/order-details/order-details')

initModalWindows()
initAuthForm()
initMessageModal()
initCatalogList()
initTownSelector()
initProductCard()
initSearchLocation()
initSearchForm()
initBannerSlider()
initShopCategory()
initProductSlider()
initSimpleSlider()
initInstructionUse()
